"""AcaBot 核心执行引擎 (Runtime Engine).

Runtime 层是将 AcaBot 各大组件拼装起来
当 Gateway 接收并解析消息后, 会将标准事件交由本层的 `RuntimeApp` 进行主循环处理

此 `__init__.py` 是 Runtime 层对外的“统一暴露点” (Facade), 集中导出了所有运行时所需的稳定基础对象,主要分为以下几个子域: 

1. 编排与调度 (Orchestration): `RuntimeApp`, `AgentRuntime`, `ThreadManager`, `RunManager`
2. 认知与记忆 (Cognition & Memory): `ModelRegistry` (模型调度), `MemoryBroker` (上下文压缩与存储)
3. 交互与沙箱 (Tools & Compute): `ToolBroker` (工具收发), `ComputerService` (终端执行与工作区隔离)
4. 身份与委派 (Identity & Delegation): `AgentProfile` (人格设定), `SubagentExecutionService` (主副 Agent 委派)

由于依赖反转, `computer` 作为物理沙箱抽象在此处定义
而将沙箱暴漏为 LLM 工具的具体适配器逻辑位于 `runtime.plugins.computer_tool_adapter`。
"""

from .agent_runtime import AgentRuntime
from .approval_resumer import (
    ApprovalResumeResult,
    ApprovalResumer,
    NoopApprovalResumer,
)
from .app import RuntimeApp
from .bootstrap import RuntimeComponents, build_runtime_components
from .computer import (
    AttachmentSnapshot,
    AttachmentStageResult,
    CommandExecutionResult,
    CommandSession,
    ComputerBackend,
    ComputerRuntimeConfig,
    ComputerPolicy,
    ComputerRuntimeOverride,
    ComputerRuntime,
    DockerSandboxBackend,
    HostComputerBackend,
    RemoteComputerBackend,
    WorkspaceFileEntry,
    WorkspaceManager,
    WorkspaceSandboxStatus,
    WorkspaceState,
    parse_computer_override,
    parse_computer_policy,
)
from .context_compactor import (
    ContextCompactionConfig,
    ContextCompactionResult,
    ContextCompactor,
    ContextSummarizer,
    ModelContextSummarizer,
    NullContextSummarizer,
)
from .control_plane import (
    ActiveRunSnapshot,
    AgentSkillSnapshot,
    AgentSwitchSnapshot,
    MemoryQuerySnapshot,
    PluginReloadSnapshot,
    RuntimeControlPlane,
    RuntimeStatusSnapshot,
    SkillSnapshot,
    SubagentExecutorSnapshot,
)
from .event_policy import EventPolicyRegistry
from .event_store import InMemoryChannelEventStore
from .memory_broker import (
    MemoryBlock,
    MemoryBroker,
    MemoryExtractor,
    MemoryRetrievalRequest,
    MemoryRetriever,
    MemoryWriteRequest,
    NullMemoryExtractor,
    NullMemoryRetriever,
)
from .memory_item_store import InMemoryMemoryStore
from .memory_store import InMemoryMessageStore
from .model_agent_runtime import (
    ModelAgentRuntime,
    ToolRuntime,
    ToolRuntimeResolver,
    ToolRuntimeState,
)
from .model_registry import (
    AnthropicProviderConfig,
    EffectiveModelSnapshot,
    FileSystemModelRegistryManager,
    GoogleGeminiProviderConfig,
    ModelBinding,
    ModelHealthCheckResult,
    ModelImpactSnapshot,
    ModelMutationResult,
    ModelProvider,
    ModelPreset,
    ModelRegistry,
    ModelRegistryStatusSnapshot,
    ModelReloadSnapshot,
    OpenAICompatibleProviderConfig,
    PersistedModelSnapshot,
    RuntimeModelRequest,
    snapshot_from_runtime_request,
)
from .models import (
    AgentProfile,
    DelegationMode,
    ApprovalRequired,
    ApprovalDecisionResult,
    AgentRuntimeResult,
    BindingRule,
    ChannelEventRecord,
    DeliveryResult,
    DispatchReport,
    EventPolicy,
    EventPolicyDecision,
    InboundRule,
    MemoryEditMode,
    MemoryItem,
    MessageRecord,
    OutboxItem,
    PendingApproval,
    PendingApprovalRecord,
    PlannedAction,
    PromptSlot,
    RecoveryReport,
    RetrievalPlan,
    RouteDecision,
    RunContext,
    RunRecord,
    RunStatus,
    RunStep,
    SkillAssignment,
    ThreadRecord,
    ThreadState,
)
from .outbox import Outbox
from .pipeline import ThreadPipeline
from .plugin_manager import (
    RuntimeHook,
    RuntimeHookPoint,
    RuntimeHookRegistry,
    RuntimeHookResult,
    RuntimePlugin,
    RuntimePluginContext,
    RuntimePluginManager,
    RuntimePluginSpec,
    RuntimeToolRegistration,
    load_runtime_plugin,
    load_runtime_plugins_from_config,
    parse_runtime_plugin_spec,
)
from .plugins import (
    ComputerToolAdapterPlugin,
    NapCatToolsPlugin,
    OpsControlPlugin,
    ReferenceToolsPlugin,
    SkillDelegationPlugin,
    StickyNotesPlugin,
)
from .profile_loader import (
    AgentProfileRegistry,
    ChainedPromptLoader,
    FileSystemBindingLoader,
    FileSystemEventPolicyLoader,
    FileSystemInboundRuleLoader,
    FileSystemProfileLoader,
    FileSystemPromptLoader,
    ProfileLoader,
    PromptLoader,
    StaticProfileLoader,
    StaticPromptLoader,
)
from .reference_backend import (
    LocalReferenceBackend,
    NullReferenceBackend,
    OpenVikingReferenceBackend,
    ReferenceBodyLevel,
    ReferenceBackend,
    ReferenceDocument,
    ReferenceDocumentInput,
    ReferenceDocumentRef,
    ReferenceHit,
    ReferenceMode,
    ReferenceProviderMode,
    ReferenceSpace,
)
from .retrieval_planner import PromptAssemblyConfig, RetrievalPlanner
from .router import InboundRuleRegistry, RuntimeRouter
from .runs import InMemoryRunManager, RunManager, StoreBackedRunManager
from .skills import (
    RegisteredSkill,
    ResolvedSkillAssignment,
    SkillRegistry,
    SkillSpec,
    SkillType,
    SubagentDelegationRequest,
    SubagentDelegationResult,
)
from .subagent_delegation import (
    RegisteredSubagentExecutor,
    SubagentDelegationBroker,
    SubagentExecutor,
    SubagentExecutorRegistration,
    SubagentExecutorRegistry,
)
from .subagent_execution import LocalSubagentExecutionService
from .sqlite_stores import (
    SQLiteChannelEventStore,
    SQLiteMemoryStore,
    SQLiteMessageStore,
    SQLiteRunStore,
    SQLiteThreadStore,
)
from .sticky_notes import StickyNotesService
from .stores import ChannelEventStore, MemoryStore, MessageStore, RunStore, ThreadStore
from .structured_memory import StoreBackedMemoryRetriever, StructuredMemoryExtractor
from .tool_broker import (
    AllowAllToolPolicy,
    InMemoryToolAudit,
    RegisteredTool,
    ToolBroker,
    ToolAudit,
    ToolAuditRecord,
    ToolPolicy,
    ToolPolicyDecision,
    ToolExecutionContext,
    ToolResult,
)
from .threads import InMemoryThreadManager, StoreBackedThreadManager, ThreadManager

__all__ = [
    "AgentRuntime",
    "AgentRuntimeResult",
    "AgentProfile",
    "AgentProfileRegistry",
    "ApprovalRequired",
    "ApprovalDecisionResult",
    "ApprovalResumeResult",
    "ApprovalResumer",
    "BindingRule",
    "ChainedPromptLoader",
    "ChannelEventRecord",
    "ChannelEventStore",
    "ComputerBackend",
    "ComputerRuntimeConfig",
    "ComputerPolicy",
    "ComputerRuntimeOverride",
    "ComputerRuntime",
    "ContextCompactionConfig",
    "ContextCompactionResult",
    "ContextCompactor",
    "ActiveRunSnapshot",
    "AgentSkillSnapshot",
    "AgentSwitchSnapshot",
    "MemoryQuerySnapshot",
    "PluginReloadSnapshot",
    "RuntimeControlPlane",
    "RuntimeStatusSnapshot",
    "SkillSnapshot",
    "SubagentExecutorSnapshot",
    "ContextSummarizer",
    "ModelContextSummarizer",
    "DeliveryResult",
    "DispatchReport",
    "DockerSandboxBackend",
    "build_runtime_components",
    "EventPolicy",
    "EventPolicyDecision",
    "EventPolicyRegistry",
    "InboundRule",
    "InboundRuleRegistry",
    "InMemoryChannelEventStore",
    "InMemoryRunManager",
    "InMemoryMessageStore",
    "InMemoryThreadManager",
    "HostComputerBackend",
    "FileSystemProfileLoader",
    "FileSystemPromptLoader",
    "FileSystemBindingLoader",
    "FileSystemInboundRuleLoader",
    "FileSystemEventPolicyLoader",
    "MemoryBlock",
    "MemoryBroker",
    "MemoryEditMode",
    "MemoryExtractor",
    "MemoryItem",
    "MemoryStore",
    "MessageRecord",
    "MessageStore",
    "MemoryRetrievalRequest",
    "MemoryRetriever",
    "MemoryWriteRequest",
    "ModelAgentRuntime",
    "ModelBinding",
    "ModelHealthCheckResult",
    "ModelImpactSnapshot",
    "ModelMutationResult",
    "ModelProvider",
    "ModelPreset",
    "ModelRegistry",
    "ModelRegistryStatusSnapshot",
    "ModelReloadSnapshot",
    "RuntimeModelRequest",
    "PersistedModelSnapshot",
    "snapshot_from_runtime_request",
    "OpenAICompatibleProviderConfig",
    "AnthropicProviderConfig",
    "GoogleGeminiProviderConfig",
    "EffectiveModelSnapshot",
    "FileSystemModelRegistryManager",
    "InMemoryMemoryStore",
    "NoopApprovalResumer",
    "NullContextSummarizer",
    "NullMemoryExtractor",
    "NullMemoryRetriever",
    "NullReferenceBackend",
    "OutboxItem",
    "OpenVikingReferenceBackend",
    "PendingApproval",
    "PendingApprovalRecord",
    "PlannedAction",
    "ProfileLoader",
    "PromptAssemblyConfig",
    "PromptLoader",
    "PromptSlot",
    "parse_computer_override",
    "parse_computer_policy",
    "RouteDecision",
    "RecoveryReport",
    "RuntimeComponents",
    "RuntimeApp",
    "RuntimeHook",
    "RuntimeHookPoint",
    "RuntimeHookRegistry",
    "RuntimeHookResult",
    "RuntimePlugin",
    "RuntimePluginContext",
    "RuntimePluginManager",
    "RuntimePluginSpec",
    "RuntimeToolRegistration",
    "DelegationMode",
    "SkillAssignment",
    "SkillType",
    "SkillSpec",
    "RegisteredSkill",
    "ResolvedSkillAssignment",
    "SkillRegistry",
    "SubagentDelegationRequest",
    "SubagentDelegationResult",
    "SubagentExecutor",
    "SubagentExecutorRegistration",
    "RegisteredSubagentExecutor",
    "SubagentExecutorRegistry",
    "SubagentDelegationBroker",
    "LocalSubagentExecutionService",
    "load_runtime_plugin",
    "load_runtime_plugins_from_config",
    "parse_runtime_plugin_spec",
    "ComputerToolAdapterPlugin",
    "NapCatToolsPlugin",
    "OpsControlPlugin",
    "ReferenceToolsPlugin",
    "SkillDelegationPlugin",
    "StickyNotesPlugin",
    "RunContext",
    "RunManager",
    "RunRecord",
    "RunStatus",
    "RunStep",
    "RunStore",
    "RuntimeRouter",
    "RetrievalPlan",
    "RetrievalPlanner",
    "Outbox",
    "SQLiteChannelEventStore",
    "SQLiteMemoryStore",
    "SQLiteMessageStore",
    "SQLiteRunStore",
    "SQLiteThreadStore",
    "StickyNotesService",
    "ReferenceBackend",
    "ReferenceBodyLevel",
    "ReferenceDocument",
    "ReferenceDocumentInput",
    "ReferenceDocumentRef",
    "ReferenceHit",
    "ReferenceMode",
    "ReferenceProviderMode",
    "ReferenceSpace",
    "LocalReferenceBackend",
    "StaticProfileLoader",
    "StaticPromptLoader",
    "StoreBackedMemoryRetriever",
    "StoreBackedRunManager",
    "StoreBackedThreadManager",
    "StructuredMemoryExtractor",
    "ThreadPipeline",
    "ThreadManager",
    "ThreadRecord",
    "ThreadState",
    "ThreadStore",
    "WorkspaceFileEntry",
    "WorkspaceManager",
    "WorkspaceSandboxStatus",
    "WorkspaceState",
    "AttachmentSnapshot",
    "AttachmentStageResult",
    "CommandExecutionResult",
    "CommandSession",
    "RemoteComputerBackend",
    "AllowAllToolPolicy",
    "InMemoryToolAudit",
    "ToolRuntime",
    "ToolRuntimeState",
    "ToolRuntimeResolver",
    "RegisteredTool",
    "ToolBroker",
    "ToolAudit",
    "ToolAuditRecord",
    "ToolPolicy",
    "ToolPolicyDecision",
    "ToolExecutionContext",
    "ToolResult",
]
