"""AcaBot 核心执行引擎 (Runtime Engine).

Runtime 层是将 AcaBot 各大组件拼装起来
当 Gateway 接收并解析消息后, 会将标准事件交由本层的 `RuntimeApp` 进行主循环处理

此 `__init__.py` 是 Runtime 层对外的“统一暴露点” (Facade), 集中导出了所有运行时所需的稳定基础对象,主要分为以下几个子域: 

1. 编排与调度 (Orchestration): `RuntimeApp`, `AgentRuntime`, `ThreadManager`, `RunManager`
2. 认知与记忆 (Cognition & Memory): `ModelRegistry` (模型调度), `MemoryBroker` (上下文压缩与存储)
3. 交互与沙箱 (Tools & Compute): `ToolBroker` (工具收发), `ComputerService` (终端执行与工作区隔离)
4. 身份与委派 (Identity & Delegation): `AgentProfile` (人格设定), `SubagentExecutionService` (主副 Agent 委派)

由于依赖反转, `computer` 作为物理沙箱抽象在此处定义.
前台基础工具的注册入口位于 `runtime.builtin_tools`.
runtime 扩展插件位于 `runtime.plugins`.
"""

from .agent_runtime import AgentRuntime
from .approval_resumer import (
    ApprovalResumeResult,
    ApprovalResumer,
    NoopApprovalResumer,
    ToolApprovalResumer,
)
from .app import RuntimeApp
from .backend import (
    BackendRequest,
    BackendSourceRef,
)
from .backend.bridge import BackendBridge
from .backend.mode_registry import BackendModeRegistry, BackendModeState
from .backend.session import (
    BackendSessionBinding,
    BackendSessionBindingStore,
    BackendSessionService,
    ConfiguredBackendSessionService,
)
from .bootstrap import RuntimeComponents, build_runtime_components
from .computer import (
    AttachmentSnapshot,
    AttachmentStageResult,
    CommandExecutionResult,
    CommandSession,
    ComputerBackend,
    ComputerRuntimeConfig,
    ComputerPolicy,
    ComputerRuntime,
    DockerSandboxBackend,
    WorldPathEditResult,
    WorldPathReadResult,
    WorldPathWriteResult,
    HostComputerBackend,
    RemoteComputerBackend,
    WorkspaceFileEntry,
    WorkspaceManager,
    WorkspaceSandboxStatus,
    WorkspaceState,
    parse_computer_policy,
)
from .context_assembly import (
    AssembledContext,
    ContextAssembler,
    ContextContribution,
    PayloadJsonWriter,
)
from .control.config_control_plane import RuntimeConfigControlPlane
from .memory.context_compactor import (
    ContextCompactionConfig,
    ContextCompactionResult,
    ContextCompactor,
    ContextSummarizer,
    ModelContextSummarizer,
    NullContextSummarizer,
)
from .memory.conversation_facts import (
    ConversationDelta,
    ConversationFact,
    ConversationFactReader,
    StoreBackedConversationFactReader,
)
from .memory.long_term_ingestor import (
    LongTermMemoryIngestor,
    LongTermMemoryWritePort,
    ThreadLtmCursor,
)
from .control.control_plane import (
    ActiveRunSnapshot,
    AgentSkillSnapshot,
    AgentSwitchSnapshot,
    PluginReloadSnapshot,
    RuntimeControlPlane,
    RuntimeStatusSnapshot,
    SkillSnapshot,
    SubagentExecutorSnapshot,
)
from .control.snapshots import BackendStatusSnapshot
from .storage.event_store import InMemoryChannelEventStore
from .memory.memory_broker import (
    FORMAL_TARGET_SLOTS,
    MemoryAssemblySpec,
    MemoryBlock,
    MemoryBroker,
    MemoryBrokerResult,
    MemorySource,
    MemorySourceFailure,
    MemorySourcePolicy,
    MemorySourceRegistry,
    SharedMemoryRetrievalRequest,
)
from .storage.memory_store import InMemoryMessageStore
from .control.http_api import RuntimeHttpApiServer
from .inbound.image_context import (
    DEFAULT_IMAGE_CAPTION_PROMPT,
    ImageCaptionSettings,
    ImageContextService,
    parse_image_caption_settings,
)
from .inbound.message_preparation import MessagePreparationService
from .inbound.message_projection import MessageProjectionService
from .inbound.message_resolution import MessageResolutionService
from .model.model_agent_runtime import (
    ModelAgentRuntime,
    ToolRuntime,
    ToolRuntimeResolver,
    ToolRuntimeState,
)
from .model.model_registry import (
    AnthropicProviderConfig,
    EffectiveModelSnapshot,
    FileSystemModelRegistryManager,
    GoogleGeminiProviderConfig,
    ModelBinding,
    ModelHealthCheckResult,
    ModelImpactSnapshot,
    ModelMutationResult,
    ModelProvider,
    ModelPreset,
    ModelRegistry,
    ModelRegistryStatusSnapshot,
    ModelReloadSnapshot,
    OpenAICompatibleProviderConfig,
    PersistedModelSnapshot,
    RuntimeModelRequest,
    snapshot_from_runtime_request,
)
from .contracts import (
    AdmissionDecision,
    AdmissionDomainConfig,
    AgentProfile,
    DelegationMode,
    ApprovalRequired,
    ApprovalDecisionResult,
    AgentRuntimeResult,
    ChannelEventRecord,
    ComputerDomainConfig,
    ComputerPolicyDecision,
    ContextDecision,
    ContextDomainConfig,
    DeliveryResult,
    DispatchReport,
    DomainCase,
    DomainConfig,
    EventFacts,
    ExtractionDecision,
    ExtractionDomainConfig,
    MatchSpec,
    MemoryCandidate,
    MemoryEditMode,
    MessageProjection,
    MessageRecord,
    OutboxItem,
    PendingApproval,
    PendingApprovalRecord,
    PersistenceDecision,
    PersistenceDomainConfig,
    PlannedAction,
    RecoveryReport,
    ResolvedImageInput,
    ResolvedMessage,
    RetrievalPlan,
    RouteDecision,
    RoutingDecision,
    RoutingDomainConfig,
    RunContext,
    RunRecord,
    RunStatus,
    RunStep,
    SequencedChannelEventRecord,
    SequencedMessageRecord,
    SessionConfig,
    SessionLocatorResult,
    SurfaceConfig,
    SurfaceResolution,
    ThreadRecord,
    ThreadState,
)
from .outbox import Outbox
from .pipeline import ThreadPipeline
from .plugin_manager import (
    RuntimeHook,
    RuntimeHookPoint,
    RuntimeHookRegistry,
    RuntimeHookResult,
    RuntimePlugin,
    RuntimePluginContext,
    RuntimePluginManager,
    RuntimePluginSpec,
    RuntimeToolRegistration,
    load_runtime_plugin,
    load_runtime_plugins_from_config,
    parse_runtime_plugin_spec,
)
from .plugins import (
    BackendBridgeToolPlugin,
    NapCatToolsPlugin,
    OpsControlPlugin,
    ReferenceToolsPlugin,
)
from .control.profile_loader import (
    AgentProfileRegistry,
    ChainedPromptLoader,
    FileSystemProfileLoader,
    FileSystemPromptLoader,
    ProfileLoader,
    PromptLoader,
    ReloadablePromptLoader,
    StaticProfileLoader,
    StaticPromptLoader,
)
from .control.session_loader import ConfigBackedSessionConfigLoader, SessionConfigLoader, StaticSessionConfigLoader
from .control.session_runtime import SessionRuntime
from .references import (
    LocalReferenceBackend,
    NullReferenceBackend,
    OpenVikingReferenceBackend,
    ReferenceBodyLevel,
    ReferenceBackend,
    ReferenceDocument,
    ReferenceDocumentInput,
    ReferenceDocumentRef,
    ReferenceHit,
    ReferenceMode,
    ReferenceProviderMode,
    ReferenceSpace,
)
from .memory.retrieval_planner import RetrievalPlanner
from .router import RuntimeRouter
from .soul import SoulSource
from .storage.runs import InMemoryRunManager, RunManager, StoreBackedRunManager
from .skills import FileSystemSkillPackageLoader
from .skills import (
    SkillPackageDocument,
    SkillPackageFormatError,
    SkillPackageManifest,
)
from .skills import SkillCatalog
from .subagents import (
    RegisteredSubagentExecutor,
    SubagentDelegationBroker,
    SubagentDelegationRequest,
    SubagentDelegationResult,
    SubagentExecutor,
    SubagentExecutorRegistration,
    SubagentExecutorRegistry,
)
from .subagents.execution import LocalSubagentExecutionService
from .storage.sqlite_stores import (
    SQLiteChannelEventStore,
    SQLiteMessageStore,
    SQLiteRunStore,
    SQLiteThreadStore,
)
from .memory.sticky_note_renderer import StickyNoteRenderer
from .memory.sticky_notes import StickyNoteService
from .memory.file_backed import StickyNoteFileStore, StickyNoteRecord
from .storage.stores import ChannelEventStore, MessageStore, RunStore, ThreadStore
from .tool_broker import (
    AllowAllToolPolicy,
    InMemoryToolAudit,
    RegisteredTool,
    ToolBroker,
    ToolAudit,
    ToolAuditRecord,
    ToolPolicy,
    ToolPolicyDecision,
    ToolExecutionContext,
    ToolReplayResult,
    ToolResult,
)
from .storage.threads import InMemoryThreadManager, StoreBackedThreadManager, ThreadManager

__all__ = [
    "AdmissionDecision",
    "AdmissionDomainConfig",
    "AgentRuntime",
    "AgentRuntimeResult",
    "AgentProfile",
    "BackendBridge",
    "BackendModeRegistry",
    "BackendModeState",
    "BackendRequest",
    "BackendSessionBinding",
    "BackendSessionBindingStore",
    "BackendSessionService",
    "ConfiguredBackendSessionService",
    "BackendSourceRef",
    "BackendStatusSnapshot",
    "AgentProfileRegistry",
    "ApprovalRequired",
    "ApprovalDecisionResult",
    "ApprovalResumeResult",
    "ApprovalResumer",
    "AssembledContext",
    "ChainedPromptLoader",
    "ChannelEventRecord",
    "SequencedChannelEventRecord",
    "ChannelEventStore",
    "ComputerDomainConfig",
    "ComputerPolicyDecision",
    "ComputerBackend",
    "ComputerRuntimeConfig",
    "ComputerPolicy",
    "ComputerRuntime",
    "WorldPathEditResult",
    "WorldPathReadResult",
    "WorldPathWriteResult",
    "RuntimeConfigControlPlane",
    "RuntimeHttpApiServer",
    "ContextCompactionConfig",
    "ContextCompactionResult",
    "ContextCompactor",
    "ContextAssembler",
    "ConversationDelta",
    "ConversationFact",
    "ConversationFactReader",
    "ActiveRunSnapshot",
    "AgentSkillSnapshot",
    "AgentSwitchSnapshot",
    "PluginReloadSnapshot",
    "RuntimeControlPlane",
    "RuntimeStatusSnapshot",
    "SkillSnapshot",
    "SubagentExecutorSnapshot",
    "StoreBackedConversationFactReader",
    "ContextSummarizer",
    "ModelContextSummarizer",
    "ContextDecision",
    "ContextContribution",
    "ContextDomainConfig",
    "DeliveryResult",
    "DispatchReport",
    "DockerSandboxBackend",
    "DomainCase",
    "DomainConfig",
    "BackendBridgeToolPlugin",
    "build_runtime_components",
    "EventFacts",
    "ExtractionDecision",
    "ExtractionDomainConfig",
    "SoulSource",
    "InMemoryChannelEventStore",
    "InMemoryRunManager",
    "InMemoryMessageStore",
    "InMemoryThreadManager",
    "HostComputerBackend",
    "ImageCaptionSettings",
    "ImageContextService",
    "FORMAL_TARGET_SLOTS",
    "MessagePreparationService",
    "MessageProjectionService",
    "MessageResolutionService",
    "FileSystemProfileLoader",
    "FileSystemPromptLoader",
    "LongTermMemoryIngestor",
    "LongTermMemoryWritePort",
    "MemoryBlock",
    "MemoryBroker",
    "MemoryBrokerResult",
    "MemoryCandidate",
    "MemoryAssemblySpec",
    "MemoryEditMode",
    "MemorySource",
    "MemorySourceFailure",
    "MemorySourcePolicy",
    "MemorySourceRegistry",
    "MessageRecord",
    "SequencedMessageRecord",
    "MessageProjection",
    "MessageStore",
    "ModelAgentRuntime",
    "ModelBinding",
    "ModelHealthCheckResult",
    "ModelImpactSnapshot",
    "ModelMutationResult",
    "ModelProvider",
    "ModelPreset",
    "ModelRegistry",
    "ModelRegistryStatusSnapshot",
    "ModelReloadSnapshot",
    "RuntimeModelRequest",
    "PersistedModelSnapshot",
    "snapshot_from_runtime_request",
    "OpenAICompatibleProviderConfig",
    "AnthropicProviderConfig",
    "GoogleGeminiProviderConfig",
    "EffectiveModelSnapshot",
    "FileSystemModelRegistryManager",
    "MatchSpec",
    "NoopApprovalResumer",
    "ToolApprovalResumer",
    "NullContextSummarizer",
    "NullReferenceBackend",
    "OutboxItem",
    "OpenVikingReferenceBackend",
    "PendingApproval",
    "PendingApprovalRecord",
    "PlannedAction",
    "ProfileLoader",
    "PromptLoader",
    "PayloadJsonWriter",
    "ReloadablePromptLoader",
    "PersistenceDecision",
    "PersistenceDomainConfig",
    "DEFAULT_IMAGE_CAPTION_PROMPT",
    "parse_image_caption_settings",
    "parse_computer_policy",
    "RouteDecision",
    "RoutingDecision",
    "SharedMemoryRetrievalRequest",
    "RoutingDomainConfig",
    "RecoveryReport",
    "ResolvedImageInput",
    "ResolvedMessage",
    "RuntimeComponents",
    "RuntimeApp",
    "RuntimeHook",
    "RuntimeHookPoint",
    "RuntimeHookRegistry",
    "RuntimeHookResult",
    "RuntimePlugin",
    "RuntimePluginContext",
    "RuntimePluginManager",
    "RuntimePluginSpec",
    "RuntimeToolRegistration",
    "DelegationMode",
    "SkillCatalog",
    "FileSystemSkillPackageLoader",
    "SkillPackageDocument",
    "SkillPackageFormatError",
    "SkillPackageManifest",
    "SubagentDelegationRequest",
    "SubagentDelegationResult",
    "SubagentExecutor",
    "SubagentExecutorRegistration",
    "RegisteredSubagentExecutor",
    "SubagentExecutorRegistry",
    "SubagentDelegationBroker",
    "LocalSubagentExecutionService",
    "load_runtime_plugin",
    "load_runtime_plugins_from_config",
    "parse_runtime_plugin_spec",
    "BackendBridgeToolPlugin",
    "NapCatToolsPlugin",
    "OpsControlPlugin",
    "ReferenceToolsPlugin",
    "RunContext",
    "RunManager",
    "RunRecord",
    "RunStatus",
    "RunStep",
    "RunStore",
    "RuntimeRouter",
    "SessionConfig",
    "SessionConfigLoader",
    "ConfigBackedSessionConfigLoader",
    "StaticSessionConfigLoader",
    "SessionLocatorResult",
    "SessionRuntime",
    "RetrievalPlan",
    "RetrievalPlanner",
    "Outbox",
    "SQLiteChannelEventStore",
    "SQLiteMessageStore",
    "SQLiteRunStore",
    "SQLiteThreadStore",
    "StickyNoteService",
    "StickyNoteFileStore",
    "StickyNoteRecord",
    "StickyNoteRenderer",
    "ReferenceBackend",
    "ReferenceBodyLevel",
    "ReferenceDocument",
    "ReferenceDocumentInput",
    "ReferenceDocumentRef",
    "ReferenceHit",
    "ReferenceMode",
    "ReferenceProviderMode",
    "ReferenceSpace",
    "LocalReferenceBackend",
    "StaticProfileLoader",
    "StaticPromptLoader",
    "StoreBackedRunManager",
    "StoreBackedThreadManager",
    "SurfaceConfig",
    "SurfaceResolution",
    "ThreadPipeline",
    "ThreadManager",
    "ThreadRecord",
    "ThreadLtmCursor",
    "ThreadState",
    "ThreadStore",
    "WorkspaceFileEntry",
    "WorkspaceManager",
    "WorkspaceSandboxStatus",
    "WorkspaceState",
    "AttachmentSnapshot",
    "AttachmentStageResult",
    "CommandExecutionResult",
    "CommandSession",
    "RemoteComputerBackend",
    "AllowAllToolPolicy",
    "InMemoryToolAudit",
    "ToolRuntime",
    "ToolRuntimeState",
    "ToolRuntimeResolver",
    "RegisteredTool",
    "ToolBroker",
    "ToolAudit",
    "ToolAuditRecord",
    "ToolPolicy",
    "ToolPolicyDecision",
    "ToolExecutionContext",
    "ToolReplayResult",
    "ToolResult",
]
